version: "3"

services:

  localstack:
    build:
      context: ./docker/localstack
    environment:
      - "HOSTNAME_EXTERNAL=localstack"
      - "AWS_CBOR_DISABLE=true"
      - "USE_SSL=true"
    ports:
      - "4568:4568"

  mysql:
    image: debezium/example-mysql:0.9
    environment:
      - MYSQL_USER=mysqluser
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_PASSWORD=mysqlpw
    ports:
      - "3306:3306"
